---
- hosts: localhost #Azure Terraform VM
  gather_facts: True
  become: yes
  tasks:
 

    - name: Pull the Docker image
      shell: docker pull joellesaurer/petclinics:devenv

    
    - name: Log into DockerHub
      docker_login:
        username: joellesaurer
        password: saurer4335
        email: joelle.saurer@devoteam.com

    - name: Tag docker image 
      shell: docker tag joellesaurer/petclinics:devenv joellesaurer/production

    - name: Push docker image
      shell: docker push joellesaurer/production