---
- hosts: localhost #Azure Terraform VM
  gather_facts: True
  tasks:


    - name: Pull the Docker image
      docker_image:
        name: joellesaurer/petclinics:devenv

    
    - name: Log into DockerHub
      docker_login:
        username: joellesaurer
        password: saurer4335
        email: docker@docker.io

    - name: Tag and push to docker hub 
      docker_image:
        name: joellesaurer/petclinics:devenv
        repository: joellesaurer/petclinics
        tag: prodenv
        push: yes
