---
- hosts: production
  gather_facts: True
 
  tasks:

    - name: Pull the Docker image
      docker_image:
        name: joellesaurer/devenv
        tag: latest
        source: pull 
        state: present 

  #run the image
    # - name: create container
    #   docker_container:
    #       name: cotainerSelenium
    #       image: joellesaurer/devenv:latest
    #       command: /opt/tomcat/bin/catalina.sh run
    #       published_ports: "8086:8080"
    #       state: present
    
    - name: Log into DockerHub
      docker_login:
        username: joellesaurer
        password: saurer4335
        email: docker@docker.io

    - name: Tag and push to docker hub
      docker_image:
        name: joellesaurer/devenv:latest
        tag: release
        push: yes