---
- hosts: localhost #Azure Terraform VM
  gather_facts: True
  tasks:


    - name: Pull the Docker image
      docker_image:
        name: joellesaurer/petclinics

    
    - name: Log into DockerHub
      docker_login:
        username: joellesaurer
        password: saurer4335
        email: docker@docker.io

    - name: Tag and push to docker hub #This might already pull and tag the image specified below and pushes it with the prodenv tag.
      docker_image:
        name: joellesaurer/petclinics:devenv
        tag: prodenv
        push: yes
