---
- hosts: localhost #Azure Terraform VM
  gather_facts: True
  become: True

  tasks:
 
    - name: Install required system packages
      apt: 
        pkg: 
          - python3-apt
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present

    - name: update apt caches
      apt: update_cache=yes force_apt_get=yes
 
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker


    - name: Pull the Docker image
      docker_image:
        name: joellesaurer/petclinic
        tag: devenv
        source: pull 
        state: present 

  #run the image
    - name: run container
      docker_container:
          name: containerSelenium
          image: joellesaurer/petclinic:devenv
          command: /opt/tomcat/bin/catalina.sh run
          published_ports: "8086:8080"
          state: present
    



  #OR you build the image IN the playbook
        # tasks:
  #   - name: create build directory
  #     file:
  #       path: /root/demo-dockerfile
  #       state: directory
  #       owner: root
  #       group: root
  #       mode: '0755'
  #   - name: copy Dockerfile
  #     copy:
  #       src: ./Dockerfile
  #       dest: /root/demo-dockerfile/Dockerfile
  #       owner: root
  #       group: root
  #       mode: '0644'
  #   - name: build container image
  #     docker_image:
  #       name: petclinics:v1.0
  #       build:
  #         path: /root/demo-dockerfile
  #         source: build
  #       state: present
