---
- hosts: localhost #Azure Terraform VM
  gather_facts: True

  tasks:
   
  #run the image
    - name: run container
      docker_container:
          name: containerSelenium
          image: joellesaurer/petclinics:devenv
          ports: 
            - "8088:8080"
          state: present