---
- hosts: localhost #Azure Terraform VM
  gather_facts: True

  tasks:
    - name: Pull the Docker image
      shell: docker pull joellesaurer/petclinics:devenv

  #run the image
    - name: run container
      shell: docker run -d -it -p 8086:8080 joellesaurer/petclinics:devenv