---
- hosts: localhost #Azure Terraform VM
  gather_facts: True

  tasks:
    - name: Pull the Docker image
      shell: docker pull joellesaurer/petclinics:devenv

  #run the image
    # - name: run container
    #   docker_container:
    #       name: containerSelenium
    #       image: joellesaurer/petclinics:devenv
    #       command: /opt/tomcat/bin/catalina.sh run 
    #       ports: 
    #         - "8088:8080"
    #       state: present